extends RefCounted
## The fabricator's catalogue — every placeable object the captain can print
## for rooms THEY built (core rooms keep their fixed stations). Curated from
## the craft sheets; costs are real chemistry in mined/scooped/traded
## elements: steel frames (Fe), alloys (Al/Ti), chips and glass (Si), wiring
## (Cu), plastics/fabric/organics (C, N, P), lamp gases (Ne/Ar/Kr/Xe),
## Nd magnets, Ag mirrors, Au trim, W crucibles, Li cells, U fuel.
## Preload as a const (same pattern as Keymap) — everything here is static.

const CATEGORIES := ["QUARTERS", "GALLEY", "SCIENCE", "ENGINEERING", "LOUNGE"]

## size = floor columns occupied in a room's placement grid (1-3).
## "flat": drawn under the crew's feet (rugs). "back": wall piece, back row only.
const ITEMS := {
	# ---- QUARTERS — somewhere to be a person again
	"bed_single":    {"name": "Single Bed", "cat": "QUARTERS", "size": 2,
		"cost": {"Fe": 4, "C": 3}, "desc": "One pillow. Zero gravity nightmares.",
		"tex": preload("res://assets/craft/bed_single.png")},
	"bed_double":    {"name": "Double Bed", "cat": "QUARTERS", "size": 2,
		"cost": {"Fe": 5, "C": 5}, "desc": "Twice the blanket to lose.",
		"tex": preload("res://assets/craft/bed_double.png")},
	"bunk_bed":      {"name": "Bunk Bed", "cat": "QUARTERS", "size": 2,
		"cost": {"Fe": 6, "C": 3}, "desc": "Crew stacks like cargo.",
		"tex": preload("res://assets/craft/bunk_bed.png")},
	"sleep_pod":     {"name": "Sleep Pod", "cat": "QUARTERS", "size": 1,
		"cost": {"Ti": 4, "Si": 3, "Xe": 1}, "desc": "Dreamless. Efficient. Cold.",
		"tex": preload("res://assets/craft/sleep_pod.png")},
	"locker":        {"name": "Locker", "cat": "QUARTERS", "size": 1,
		"cost": {"Fe": 4}, "desc": "A door between you and the mess.",
		"tex": preload("res://assets/craft/locker.png")},
	"wardrobe":      {"name": "Wardrobe", "cat": "QUARTERS", "size": 2,
		"cost": {"Fe": 5, "Al": 2}, "desc": "Three suits, all the same suit.",
		"tex": preload("res://assets/craft/wardrobe.png")},
	"dresser":       {"name": "Dresser", "cat": "QUARTERS", "size": 2,
		"cost": {"Fe": 4, "C": 2}, "desc": "Drawers that stay shut in turbulence.",
		"tex": preload("res://assets/craft/dresser.png")},
	"nightstand":    {"name": "Nightstand", "cat": "QUARTERS", "size": 1,
		"cost": {"Fe": 2, "C": 2}, "desc": "Lamp, book, dog tags.",
		"tex": preload("res://assets/craft/nightstand.png")},
	"desk_terminal": {"name": "Work Desk", "cat": "QUARTERS", "size": 2,
		"cost": {"Fe": 3, "Si": 3, "Cu": 2}, "desc": "For logs nobody will read.",
		"tex": preload("res://assets/craft/desk_terminal.png")},
	"desk_chair":    {"name": "Desk Chair", "cat": "QUARTERS", "size": 1,
		"cost": {"Fe": 2, "C": 2}, "desc": "Swivels. Morale critical.",
		"tex": preload("res://assets/craft/desk_chair.png")},
	"bookshelf":     {"name": "Bookshelf", "cat": "QUARTERS", "size": 1,
		"cost": {"Fe": 3, "C": 4}, "desc": "Real paper. Smuggler's luxury.",
		"tex": preload("res://assets/craft/bookshelf.png")},
	"rug_round":     {"name": "Round Rug", "cat": "QUARTERS", "size": 2, "flat": true,
		"cost": {"C": 5}, "desc": "Ties the vacuum together.",
		"tex": preload("res://assets/craft/rug_round.png")},
	"floor_lamp":    {"name": "Floor Lamp", "cat": "QUARTERS", "size": 1,
		"cost": {"Al": 2, "W": 1, "Ar": 1}, "desc": "Argon glow, tungsten heart.",
		"tex": preload("res://assets/craft/floor_lamp.png")},
	"pet_bed":       {"name": "Pet Bed", "cat": "QUARTERS", "size": 1,
		"cost": {"C": 4}, "desc": "For whoever adopts whom.",
		"tex": preload("res://assets/craft/pet_bed.png")},
	"vanity_mirror": {"name": "Vanity Table", "cat": "QUARTERS", "size": 2,
		"cost": {"Si": 3, "Al": 2, "Ar": 1}, "desc": "Lit like a leading role.",
		"tex": preload("res://assets/craft/vanity_mirror.png")},
	"standing_mirror": {"name": "Standing Mirror", "cat": "QUARTERS", "size": 1,
		"cost": {"Si": 3, "Fe": 1}, "desc": "The suit still fits.",
		"tex": preload("res://assets/craft/standing_mirror.png")},
	"ottoman":       {"name": "Ottoman", "cat": "QUARTERS", "size": 1,
		"cost": {"C": 3}, "desc": "Feet up. Universe off.",
		"tex": preload("res://assets/craft/ottoman.png")},
	"footlocker":    {"name": "Footlocker", "cat": "QUARTERS", "size": 1,
		"cost": {"Fe": 3}, "desc": "Everything you own, one box.",
		"tex": preload("res://assets/craft/footlocker.png")},
	"folding_screen": {"name": "Folding Screen", "cat": "QUARTERS", "size": 2,
		"cost": {"C": 3, "Al": 2}, "desc": "Privacy, the polite fiction.",
		"tex": preload("res://assets/craft/folding_screen.png")},
	"painting":      {"name": "Painting", "cat": "QUARTERS", "size": 1,
		"cost": {"C": 2, "Au": 1}, "desc": "Saturn, from memory.",
		"tex": preload("res://assets/craft/painting.png")},
	"bench_seat":    {"name": "Padded Bench", "cat": "QUARTERS", "size": 2,
		"cost": {"Fe": 3, "C": 3}, "desc": "Boot-lacing headquarters.",
		"tex": preload("res://assets/craft/bench_seat.png")},
	"side_table":    {"name": "Side Table", "cat": "QUARTERS", "size": 1,
		"cost": {"Fe": 2, "C": 2}, "desc": "A photo of the old sky.",
		"tex": preload("res://assets/craft/side_table.png")},
	"wall_shelf":    {"name": "Wall Shelf", "cat": "QUARTERS", "size": 1, "back": true,
		"cost": {"Fe": 2, "C": 2}, "desc": "Books at eye level.",
		"tex": preload("res://assets/craft/wall_shelf.png")},
	"luggage":       {"name": "Luggage Stack", "cat": "QUARTERS", "size": 1,
		"cost": {"C": 4, "Fe": 1}, "desc": "Packed for a trip that never left.",
		"tex": preload("res://assets/craft/luggage.png")},

	# ---- GALLEY — the ship runs on its stomach
	"kitchen_counter": {"name": "Kitchen Counter", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 4, "Al": 3}, "desc": "Chop, plate, repeat.",
		"tex": preload("res://assets/craft/kitchen_counter.png")},
	"sink_unit":     {"name": "Sink Unit", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 3, "Cu": 3}, "desc": "Recycled water, honest dishes.",
		"tex": preload("res://assets/craft/sink_unit.png")},
	"stove":         {"name": "Stove & Oven", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 5, "Ni": 2, "Cu": 2}, "desc": "Nichrome coils, real heat.",
		"tex": preload("res://assets/craft/stove.png")},
	"fridge":        {"name": "Fridge", "cat": "GALLEY", "size": 1,
		"cost": {"Fe": 4, "Al": 2, "N": 2}, "desc": "Nitrogen-chilled leftovers.",
		"tex": preload("res://assets/craft/fridge.png")},
	"microwave_station": {"name": "Microwave Station", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 3, "Cu": 3, "Si": 1}, "desc": "Dinner in ninety seconds.",
		"tex": preload("res://assets/craft/microwave_station.png")},
	"coffee_bar":    {"name": "Coffee Bar", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 2, "Cu": 2, "C": 3}, "desc": "The real life support.",
		"tex": preload("res://assets/craft/coffee_bar.png")},
	"prep_station":  {"name": "Prep Station", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 3, "C": 3}, "desc": "A board that's seen things.",
		"tex": preload("res://assets/craft/prep_station.png")},
	"pantry":        {"name": "Pantry Cabinet", "cat": "GALLEY", "size": 1,
		"cost": {"Fe": 3, "Si": 2}, "desc": "Jars against the dark.",
		"tex": preload("res://assets/craft/pantry.png")},
	"dining_table":  {"name": "Dining Table", "cat": "GALLEY", "size": 3,
		"cost": {"Fe": 4, "C": 6}, "desc": "Six seats. Earn the crowd.",
		"tex": preload("res://assets/craft/dining_table.png")},
	"cafe_table":    {"name": "Café Table", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 2, "C": 3}, "desc": "Two chairs, one view.",
		"tex": preload("res://assets/craft/cafe_table.png")},
	"bar_counter":   {"name": "Bar Counter", "cat": "GALLEY", "size": 3,
		"cost": {"Fe": 5, "C": 5, "Ne": 1}, "desc": "Neon trim. House rules.",
		"tex": preload("res://assets/craft/bar_counter.png")},
	"vending_machine": {"name": "Vending Machine", "cat": "GALLEY", "size": 1,
		"cost": {"Fe": 4, "Si": 2, "Cu": 2}, "desc": "Eats coins, mostly pays out.",
		"tex": preload("res://assets/craft/vending_machine.png")},
	"water_cooler":  {"name": "Water Cooler", "cat": "GALLEY", "size": 1,
		"cost": {"Al": 2, "H": 2, "O": 1}, "desc": "Gossip congregation point.",
		"tex": preload("res://assets/craft/water_cooler.png")},
	"recycler":      {"name": "Recycler Bins", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 4, "Al": 2}, "desc": "Nothing on this ship is trash.",
		"tex": preload("res://assets/craft/recycler.png")},
	"espresso_machine": {"name": "Espresso Machine", "cat": "GALLEY", "size": 1,
		"cost": {"Fe": 2, "Cu": 2, "C": 1}, "desc": "Nine bars of civilization.",
		"tex": preload("res://assets/craft/espresso_machine.png")},
	"popcorn_machine": {"name": "Popcorn Machine", "cat": "GALLEY", "size": 1,
		"cost": {"Fe": 2, "Si": 2, "C": 1}, "desc": "Movie night fuel.",
		"tex": preload("res://assets/craft/popcorn_machine.png")},
	"dish_rack":     {"name": "Dish Station", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 3}, "desc": "Whoever cooks doesn't wash.",
		"tex": preload("res://assets/craft/dish_rack.png")},
	"freezer":       {"name": "Deep Freezer", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 4, "Al": 2, "N": 3}, "desc": "Colder than outside. Almost.",
		"tex": preload("res://assets/craft/freezer.png")},
	"produce_rack":  {"name": "Produce Rack", "cat": "GALLEY", "size": 2,
		"cost": {"Al": 3, "C": 2, "N": 1}, "desc": "Fresh, or a good imitation.",
		"tex": preload("res://assets/craft/produce_rack.png")},
	"booth_table":   {"name": "Diner Booth", "cat": "GALLEY", "size": 2,
		"cost": {"Fe": 3, "C": 4}, "desc": "Slide in. Stay a while.",
		"tex": preload("res://assets/craft/booth_table.png")},
	"brew_urn":      {"name": "Brew Urn", "cat": "GALLEY", "size": 1,
		"cost": {"Fe": 3, "Cu": 1}, "desc": "Forty cups before breakfast.",
		"tex": preload("res://assets/craft/brew_urn.png")},
	"stand_mixer":   {"name": "Stand Mixer", "cat": "GALLEY", "size": 1,
		"cost": {"Fe": 2, "Cu": 2}, "desc": "Dough waits for no one.",
		"tex": preload("res://assets/craft/stand_mixer.png")},
	"rice_cooker":   {"name": "Rice Cooker", "cat": "GALLEY", "size": 1,
		"cost": {"Fe": 2, "Si": 1}, "desc": "Perfect every orbit.",
		"tex": preload("res://assets/craft/rice_cooker.png")},
	"serving_cart":  {"name": "Serving Cart", "cat": "GALLEY", "size": 1,
		"cost": {"Al": 3, "Fe": 1}, "desc": "Dinner rolls on wheels.",
		"tex": preload("res://assets/craft/serving_cart.png")},

	# ---- SCIENCE — medbay, lab and green things
	"med_bed":       {"name": "Med Bed", "cat": "SCIENCE", "size": 2,
		"cost": {"Al": 4, "Ag": 1, "C": 2}, "desc": "Silver-lined, germ-hated.",
		"tex": preload("res://assets/craft/med_bed.png")},
	"body_scanner":  {"name": "Body Scanner", "cat": "SCIENCE", "size": 3,
		"cost": {"Ti": 4, "Si": 4, "Nd": 2}, "desc": "Neodymium magnets, no secrets.",
		"tex": preload("res://assets/craft/body_scanner.png")},
	"medicine_cabinet": {"name": "Medicine Cabinet", "cat": "SCIENCE", "size": 1,
		"cost": {"Al": 3, "Si": 2}, "desc": "Everything expires eventually.",
		"tex": preload("res://assets/craft/medicine_cabinet.png")},
	"surgery_light": {"name": "Surgery Light", "cat": "SCIENCE", "size": 1,
		"cost": {"Al": 2, "W": 1, "Kr": 1}, "desc": "Krypton-bright, shadow-free.",
		"tex": preload("res://assets/craft/surgery_light.png")},
	"lab_bench":     {"name": "Chemistry Bench", "cat": "SCIENCE", "size": 2,
		"cost": {"Fe": 3, "Si": 4}, "desc": "Flasks of maybe-progress.",
		"tex": preload("res://assets/craft/lab_bench.png")},
	"microscope_desk": {"name": "Microscope Desk", "cat": "SCIENCE", "size": 2,
		"cost": {"Fe": 2, "Si": 3, "Cu": 2}, "desc": "The small stuff matters.",
		"tex": preload("res://assets/craft/microscope_desk.png")},
	"holo_table":    {"name": "Holo Table", "cat": "SCIENCE", "size": 2,
		"cost": {"Ti": 3, "Si": 4, "Ga": 2}, "desc": "Gallium chips paint the void.",
		"tex": preload("res://assets/craft/holo_table.png")},
	"server_rack":   {"name": "Server Rack", "cat": "SCIENCE", "size": 1,
		"cost": {"Fe": 3, "Si": 5, "Cu": 3, "Au": 1}, "desc": "Gold contacts, cold logic.",
		"tex": preload("res://assets/craft/server_rack.png")},
	"stasis_tube":   {"name": "Stasis Tube", "cat": "SCIENCE", "size": 1,
		"cost": {"Ti": 4, "Si": 3, "Xe": 2}, "desc": "Xenon sleep for one.",
		"tex": preload("res://assets/craft/stasis_tube.png")},
	"specimen_tank": {"name": "Specimen Tank", "cat": "SCIENCE", "size": 1,
		"cost": {"Si": 4, "S": 2}, "desc": "Do not tap the glass.",
		"tex": preload("res://assets/craft/specimen_tank.png")},
	"hydroponic_tray": {"name": "Hydroponic Tray", "cat": "SCIENCE", "size": 2,
		"cost": {"Al": 3, "N": 2, "P": 2}, "desc": "Salad without soil.",
		"tex": preload("res://assets/craft/hydroponic_tray.png")},
	"grow_rack":     {"name": "Grow Rack", "cat": "SCIENCE", "size": 1,
		"cost": {"Al": 3, "N": 2, "P": 2}, "desc": "Two shelves of stubborn green.",
		"tex": preload("res://assets/craft/grow_rack.png")},
	"terrarium_dome": {"name": "Terrarium Dome", "cat": "SCIENCE", "size": 2,
		"cost": {"Si": 5, "C": 2, "N": 1}, "desc": "A forest, pocket-sized.",
		"tex": preload("res://assets/craft/terrarium_dome.png")},
	"algae_tank":    {"name": "Algae Tank", "cat": "SCIENCE", "size": 1,
		"cost": {"Si": 3, "N": 2, "H": 1}, "desc": "Breakfast is photosynthesizing.",
		"tex": preload("res://assets/craft/algae_tank.png")},
	"centrifuge":    {"name": "Centrifuge", "cat": "SCIENCE", "size": 2,
		"cost": {"Fe": 3, "Cu": 2, "Nd": 1}, "desc": "Spins secrets out of samples.",
		"tex": preload("res://assets/craft/centrifuge.png")},
	"sample_fridge": {"name": "Cryo Sample Fridge", "cat": "SCIENCE", "size": 1,
		"cost": {"Al": 3, "Si": 2, "N": 2}, "desc": "Do not eat the samples.",
		"tex": preload("res://assets/craft/sample_fridge.png")},
	"uv_light":      {"name": "UV Grow Bar", "cat": "SCIENCE", "size": 2,
		"cost": {"Al": 2, "Ar": 1, "W": 1}, "desc": "Violet daylight on demand.",
		"tex": preload("res://assets/craft/uv_light.png")},
	"seedling_table": {"name": "Seedling Table", "cat": "SCIENCE", "size": 2,
		"cost": {"Al": 3, "N": 2, "P": 1}, "desc": "Rows of tiny green futures.",
		"tex": preload("res://assets/craft/seedling_table.png")},
	"water_purifier": {"name": "Water Purifier", "cat": "SCIENCE", "size": 2,
		"cost": {"Fe": 3, "H": 2, "O": 1}, "desc": "Yesterday's water, tomorrow.",
		"tex": preload("res://assets/craft/water_purifier.png")},
	"robot_arm":     {"name": "Robot Arm", "cat": "SCIENCE", "size": 2,
		"cost": {"Ti": 3, "Cu": 3, "Si": 2}, "desc": "Steadier hands than yours.",
		"tex": preload("res://assets/craft/robot_arm.png")},
	"lab_console":   {"name": "Lab Console", "cat": "SCIENCE", "size": 2,
		"cost": {"Fe": 3, "Si": 4, "Cu": 2}, "desc": "Runs the numbers twice.",
		"tex": preload("res://assets/craft/lab_console.png")},
	"ecg_monitor":   {"name": "Vitals Monitor", "cat": "SCIENCE", "size": 2,
		"cost": {"Al": 2, "Si": 3, "Ag": 1}, "desc": "A steady line is good news.",
		"tex": preload("res://assets/craft/ecg_monitor.png")},
	"culture_cylinder": {"name": "Culture Cylinder", "cat": "SCIENCE", "size": 1,
		"cost": {"Si": 4, "N": 1, "H": 1}, "desc": "Green things learning to swim.",
		"tex": preload("res://assets/craft/culture_cylinder.png")},
	"herb_cabinet":  {"name": "Herb Cabinet", "cat": "SCIENCE", "size": 1,
		"cost": {"Si": 3, "C": 2, "N": 1}, "desc": "MIRA labels everything twice.",
		"tex": preload("res://assets/craft/herb_cabinet.png")},

	# ---- ENGINEERING — the loud end of the ship
	"cargo_crate":   {"name": "Cargo Crate", "cat": "ENGINEERING", "size": 1,
		"cost": {"Fe": 3}, "desc": "Stackable. Sittable. Kickable.",
		"tex": preload("res://assets/craft/cargo_crate.png")},
	"crate_stack":   {"name": "Crate Pallet", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 5, "Al": 2}, "desc": "Looks like honest work.",
		"tex": preload("res://assets/craft/crate_stack.png")},
	"storage_shelf": {"name": "Storage Shelf", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 4, "Al": 2}, "desc": "A place for every part.",
		"tex": preload("res://assets/craft/storage_shelf.png")},
	"tool_wall":     {"name": "Tool Wall", "cat": "ENGINEERING", "size": 2, "back": true,
		"cost": {"Fe": 4, "W": 1}, "desc": "Tungsten-tipped and organized.",
		"tex": preload("res://assets/craft/tool_wall.png")},
	"generator":     {"name": "Generator", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 5, "Cu": 4, "Ni": 2}, "desc": "The hum you stop hearing.",
		"tex": preload("res://assets/craft/generator.png")},
	"reactor_core":  {"name": "Reactor Core", "cat": "ENGINEERING", "size": 2,
		"cost": {"Ti": 5, "W": 2, "U": 1}, "desc": "A tame star in a cage.",
		"tex": preload("res://assets/craft/reactor_core.png")},
	"battery_bank":  {"name": "Battery Bank", "cat": "ENGINEERING", "size": 1,
		"cost": {"Li": 1, "Ni": 2, "Al": 2}, "desc": "Lithium for rainy lightyears.",
		"tex": preload("res://assets/craft/battery_bank.png")},
	"fuel_tank":     {"name": "Fuel Tank", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 4, "H": 3}, "desc": "Hydrogen, handle with respect.",
		"tex": preload("res://assets/craft/fuel_tank.png")},
	"gas_rack":      {"name": "Gas Cylinder Rack", "cat": "ENGINEERING", "size": 1,
		"cost": {"Fe": 3, "Ar": 1, "He": 1}, "desc": "Squeaky-voice hazard.",
		"tex": preload("res://assets/craft/gas_rack.png")},
	"smelter":       {"name": "Smelter", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 6, "W": 2}, "desc": "Tungsten crucible, ore in, ingots out.",
		"tex": preload("res://assets/craft/smelter.png")},
	"laser_cutter":  {"name": "Laser Cutter", "cat": "ENGINEERING", "size": 2,
		"cost": {"Ti": 3, "Si": 2, "Nd": 1, "Ag": 1}, "desc": "Nd:YAG. Measures once.",
		"tex": preload("res://assets/craft/laser_cutter.png")},
	"workbench_arm": {"name": "Assembly Bench", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 4, "Cu": 3, "Si": 2}, "desc": "The arm never sleeps.",
		"tex": preload("res://assets/craft/workbench_arm.png")},
	"conveyor":      {"name": "Conveyor Belt", "cat": "ENGINEERING", "size": 3,
		"cost": {"Fe": 5, "Cu": 2, "C": 2}, "desc": "Forward is a lifestyle.",
		"tex": preload("res://assets/craft/conveyor.png")},
	"coolant_tank":  {"name": "Coolant Tank", "cat": "ENGINEERING", "size": 1,
		"cost": {"Al": 3, "N": 3}, "desc": "Liquid nitrogen lullaby.",
		"tex": preload("res://assets/craft/coolant_tank.png")},
	"forklift":      {"name": "Forklift", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 6, "Ni": 2, "C": 2}, "desc": "Certified operators only.",
		"tex": preload("res://assets/craft/forklift.png")},
	"winch":         {"name": "Cable Winch", "cat": "ENGINEERING", "size": 1,
		"cost": {"Fe": 5, "W": 1}, "desc": "Pulls its weight, and yours.",
		"tex": preload("res://assets/craft/winch.png")},
	"pipe_valve":    {"name": "Valve Assembly", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 4, "Cu": 1}, "desc": "Righty-tighty saves lives.",
		"tex": preload("res://assets/craft/pipe_valve.png")},
	"fan_unit":      {"name": "Vent Fan", "cat": "ENGINEERING", "size": 1,
		"cost": {"Fe": 3, "Cu": 2, "Al": 1}, "desc": "The breeze is artisanal.",
		"tex": preload("res://assets/craft/fan_unit.png")},
	"tesla_coil":    {"name": "Tesla Coil", "cat": "ENGINEERING", "size": 1,
		"cost": {"Cu": 5, "Fe": 2, "W": 1}, "desc": "Do not lick. VEGA has a list.",
		"tex": preload("res://assets/craft/tesla_coil.png")},
	"barrier":       {"name": "Safety Barrier", "cat": "ENGINEERING", "size": 1,
		"cost": {"Fe": 2}, "desc": "The stripes mean business.",
		"tex": preload("res://assets/craft/barrier.png")},
	"gear_press":    {"name": "Gear Press", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 5, "Cu": 2}, "desc": "Teeth that never skip.",
		"tex": preload("res://assets/craft/gear_press.png")},
	"lathe":         {"name": "Lathe", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 5, "W": 1}, "desc": "Round is a discipline.",
		"tex": preload("res://assets/craft/lathe.png")},
	"gantry_crane":  {"name": "Gantry Crane", "cat": "ENGINEERING", "size": 2,
		"cost": {"Fe": 6, "Al": 2}, "desc": "Lifts what the forklift won't.",
		"tex": preload("res://assets/craft/gantry_crane.png")},
	"fuel_canister": {"name": "Fuel Canister", "cat": "ENGINEERING", "size": 1,
		"cost": {"Fe": 2, "H": 2}, "desc": "Handle like it's angry.",
		"tex": preload("res://assets/craft/fuel_canister.png")},

	# ---- LOUNGE — proof there's a life worth hauling ore for
	"sofa":          {"name": "Sofa", "cat": "LOUNGE", "size": 3,
		"cost": {"Fe": 3, "C": 6}, "desc": "Claims you like gravity.",
		"tex": preload("res://assets/craft/sofa.png")},
	"armchair":      {"name": "Armchair", "cat": "LOUNGE", "size": 1,
		"cost": {"Fe": 2, "C": 4}, "desc": "The captain's other seat.",
		"tex": preload("res://assets/craft/armchair.png")},
	"bean_bag":      {"name": "Bean Bag", "cat": "LOUNGE", "size": 1,
		"cost": {"C": 5}, "desc": "Swallows crew whole.",
		"tex": preload("res://assets/craft/bean_bag.png")},
	"coffee_table":  {"name": "Coffee Table", "cat": "LOUNGE", "size": 2,
		"cost": {"Fe": 2, "C": 3}, "desc": "Mug ring museum.",
		"tex": preload("res://assets/craft/coffee_table.png")},
	"arcade_cabinet": {"name": "Arcade Cabinet", "cat": "LOUNGE", "size": 1,
		"cost": {"Fe": 3, "Si": 3, "Cu": 2, "Ne": 1}, "desc": "High score: VEGA. Always VEGA.",
		"tex": preload("res://assets/craft/arcade_cabinet.png")},
	"jukebox":       {"name": "Jukebox", "cat": "LOUNGE", "size": 1,
		"cost": {"Fe": 3, "Si": 2, "Ne": 2, "Au": 1}, "desc": "Neon soul, gold trim.",
		"tex": preload("res://assets/craft/jukebox.png")},
	"pool_table":    {"name": "Pool Table", "cat": "LOUNGE", "size": 3,
		"cost": {"Fe": 4, "C": 6, "Ca": 1}, "desc": "Chalk included. Excuses aren't.",
		"tex": preload("res://assets/craft/pool_table.png")},
	"foosball":      {"name": "Foosball Table", "cat": "LOUNGE", "size": 2,
		"cost": {"Fe": 3, "C": 4}, "desc": "No spinning. HALE spins.",
		"tex": preload("res://assets/craft/foosball.png")},
	"holo_chess":    {"name": "Holo Chess", "cat": "LOUNGE", "size": 2,
		"cost": {"Si": 4, "Ga": 2, "Cu": 2}, "desc": "MIRA is undefeated.",
		"tex": preload("res://assets/craft/holo_chess.png")},
	"telescope":     {"name": "Telescope", "cat": "LOUNGE", "size": 1,
		"cost": {"Al": 4, "Si": 3, "Ag": 1}, "desc": "Silver mirror, older stars.",
		"tex": preload("res://assets/craft/telescope.png")},
	"aquarium":      {"name": "Aquarium", "cat": "LOUNGE", "size": 2,
		"cost": {"Si": 5, "H": 2, "O": 1}, "desc": "Fish who never knew Earth.",
		"tex": preload("res://assets/craft/aquarium.png")},
	"bonsai":        {"name": "Bonsai Tree", "cat": "LOUNGE", "size": 1,
		"cost": {"C": 3, "N": 2, "P": 1}, "desc": "Patience, potted.",
		"tex": preload("res://assets/craft/bonsai.png")},
	"fountain":      {"name": "Fountain", "cat": "LOUNGE", "size": 2,
		"cost": {"Si": 3, "Ca": 2, "H": 2}, "desc": "Running water, running late.",
		"tex": preload("res://assets/craft/fountain.png")},
	"fireplace":     {"name": "Plasma Fireplace", "cat": "LOUNGE", "size": 2,
		"cost": {"Fe": 4, "Si": 2, "Ar": 2}, "desc": "Argon flames, zero smoke.",
		"tex": preload("res://assets/craft/fireplace.png")},
	"potted_plant":  {"name": "Potted Plant", "cat": "LOUNGE", "size": 1,
		"cost": {"C": 2, "N": 1, "P": 1}, "desc": "Photosynthesizing morale.",
		"tex": preload("res://assets/craft/potted_plant.png")},
	"alien_plant":   {"name": "Alien Plant", "cat": "LOUNGE", "size": 1,
		"cost": {"C": 3, "N": 2, "Xe": 1}, "desc": "It watches back. Probably fine.",
		"tex": preload("res://assets/craft/alien_plant.png")},
	"crystal_planter": {"name": "Crystal Planter", "cat": "LOUNGE", "size": 1,
		"cost": {"Si": 3, "Nd": 1, "C": 2}, "desc": "Grows carats, not carrots.",
		"tex": preload("res://assets/craft/crystal_planter.png")},
	"trophy_case":   {"name": "Trophy Case", "cat": "LOUNGE", "size": 2,
		"cost": {"Si": 3, "Au": 2, "Ag": 1}, "desc": "Victories under glass.",
		"tex": preload("res://assets/craft/trophy_case.png")},
	"gold_bust":     {"name": "Gold Bust", "cat": "LOUNGE", "size": 1,
		"cost": {"Au": 3, "Ca": 2}, "desc": "Of nobody in particular.",
		"tex": preload("res://assets/craft/gold_bust.png")},
	"armillary":     {"name": "Armillary Sphere", "cat": "LOUNGE", "size": 1,
		"cost": {"Au": 2, "Cu": 3}, "desc": "Brass rings, dead reckoning.",
		"tex": preload("res://assets/craft/armillary.png")},
	"dance_pad":     {"name": "Dance Pad", "cat": "LOUNGE", "size": 2,
		"cost": {"Si": 3, "Cu": 2, "Ne": 2}, "desc": "SOLA is secretly amazing.",
		"tex": preload("res://assets/craft/dance_pad.png")},
	"poker_table":   {"name": "Poker Table", "cat": "LOUNGE", "size": 2,
		"cost": {"Fe": 3, "C": 5}, "desc": "HALE bluffs. Everyone knows.",
		"tex": preload("res://assets/craft/poker_table.png")},
	"dartboard":     {"name": "Dartboard", "cat": "LOUNGE", "size": 1,
		"cost": {"C": 3, "Fe": 1}, "desc": "Regulation distance, painted line.",
		"tex": preload("res://assets/craft/dartboard.png")},
	"synth_keyboard": {"name": "Synth Keyboard", "cat": "LOUNGE", "size": 2,
		"cost": {"Si": 3, "Cu": 2, "C": 2}, "desc": "Eighty-eight keys to elsewhere.",
		"tex": preload("res://assets/craft/synth_keyboard.png")},
	"turntable":     {"name": "Turntable", "cat": "LOUNGE", "size": 1,
		"cost": {"Fe": 2, "Si": 2, "Au": 1}, "desc": "Vinyl survived the apocalypse.",
		"tex": preload("res://assets/craft/turntable.png")},
	"planetarium":   {"name": "Planetarium", "cat": "LOUNGE", "size": 1,
		"cost": {"Ti": 3, "Si": 3, "Nd": 1}, "desc": "The sky, before the wall.",
		"tex": preload("res://assets/craft/planetarium.png")},
	"hedge_wall":    {"name": "Hedge Wall", "cat": "LOUNGE", "size": 2,
		"cost": {"C": 4, "N": 2}, "desc": "A garden, standing at attention.",
		"tex": preload("res://assets/craft/hedge_wall.png")},
	"gem_case":      {"name": "Gem Display", "cat": "LOUNGE", "size": 1,
		"cost": {"Si": 4, "Nd": 1, "Au": 1}, "desc": "The best of what you dug.",
		"tex": preload("res://assets/craft/gem_case.png")},
	"star_chart":    {"name": "Star Chart", "cat": "LOUNGE", "size": 1, "back": true,
		"cost": {"C": 2, "Au": 1, "Si": 1}, "desc": "Routes home, hand-inked.",
		"tex": preload("res://assets/craft/star_chart.png")},
	"banner":        {"name": "Ship Banner", "cat": "LOUNGE", "size": 1, "back": true,
		"cost": {"C": 3, "Au": 1}, "desc": "Colors of a one-ship fleet.",
		"tex": preload("res://assets/craft/banner.png")},
}

## Recipes known from day one — the essentials of moving in.
## Everything else shows dimmed with "no recipe yet" until a wreck coughs
## up its blueprint.
const STARTERS := [
	"bed_single", "locker", "nightstand", "desk_chair", "desk_terminal", "rug_round",
	"kitchen_counter", "sink_unit", "stove", "fridge", "cafe_table", "water_cooler",
	"med_bed", "medicine_cabinet", "lab_bench", "hydroponic_tray",
	"cargo_crate", "storage_shelf", "tool_wall", "battery_bank", "generator",
	"sofa", "coffee_table", "potted_plant", "bean_bag", "jukebox",
]

## The fabricator station's own art — NEVER a craftable.
const FABRICATOR_TEX := preload("res://assets/craft/fabricator.png")

# ==================================================================
# Derelict wrecks (flight mode) — each carries a lost recipe
# ==================================================================
const WRECKS := [
	preload("res://assets/wrecks/wreck_00.png"),
	preload("res://assets/wrecks/wreck_01.png"),
	preload("res://assets/wrecks/wreck_02.png"),
	preload("res://assets/wrecks/wreck_03.png"),
	preload("res://assets/wrecks/wreck_04.png"),
	preload("res://assets/wrecks/wreck_05.png"),
	preload("res://assets/wrecks/wreck_06.png"),
	preload("res://assets/wrecks/wreck_07.png"),
	preload("res://assets/wrecks/wreck_08.png"),
	preload("res://assets/wrecks/wreck_09.png"),
	preload("res://assets/wrecks/wreck_10.png"),
	preload("res://assets/wrecks/wreck_11.png"),
	preload("res://assets/wrecks/wreck_12.png"),
	preload("res://assets/wrecks/wreck_13.png"),
	preload("res://assets/wrecks/wreck_14.png"),
	preload("res://assets/wrecks/wreck_15.png"),
	preload("res://assets/wrecks/wreck_16.png"),
	preload("res://assets/wrecks/wreck_17.png"),
	preload("res://assets/wrecks/wreck_18.png"),
	preload("res://assets/wrecks/wreck_19.png"),
]
## Rare hulls — medical ships and dead stations. Bigger scrap haul,
## and their recipe is drawn from the fancy end of the catalogue.
const RARE_WRECKS := [12, 13, 14, 15, 17, 18, 19]


# ==================================================================
# Display widths — hand-tuned px per object, SAME SCALE as the core
# rooms' ROOM_PROPS (crew ≈ 34px tall; kit locker 28, bunk 62). The
# slot count above is the placement FOOTPRINT; this is how big the
# art actually draws, so a nightstand stays small and a bed reads as
# a bed instead of both being stretched to their slot span.
# ==================================================================
const WIDTHS := {
	# quarters — anchor points from ROOM_PROPS: bunk 62, nightstand 34, locker 28
	"bed_single": 48, "bed_double": 58, "bunk_bed": 44, "sleep_pod": 30,
	"locker": 28, "wardrobe": 42, "dresser": 40, "nightstand": 30,
	"desk_terminal": 50, "desk_chair": 26, "bookshelf": 30, "rug_round": 46,
	"floor_lamp": 20, "pet_bed": 28, "vanity_mirror": 42, "standing_mirror": 22,
	"ottoman": 24, "footlocker": 28, "folding_screen": 38, "painting": 26,
	"bench_seat": 40, "side_table": 26, "wall_shelf": 30, "luggage": 28,
	# galley
	"kitchen_counter": 50, "sink_unit": 46, "stove": 46, "fridge": 30,
	"microwave_station": 42, "coffee_bar": 42, "prep_station": 44, "pantry": 30,
	"dining_table": 70, "cafe_table": 50, "bar_counter": 64, "vending_machine": 28,
	"water_cooler": 22, "recycler": 42, "espresso_machine": 24,
	"popcorn_machine": 26, "dish_rack": 42, "freezer": 46, "produce_rack": 44,
	"booth_table": 52, "brew_urn": 22, "stand_mixer": 22, "rice_cooker": 22,
	"serving_cart": 28,
	# science
	"med_bed": 50, "body_scanner": 62, "medicine_cabinet": 28, "surgery_light": 28,
	"lab_bench": 48, "microscope_desk": 46, "holo_table": 46, "server_rack": 28,
	"stasis_tube": 28, "specimen_tank": 28, "hydroponic_tray": 46, "grow_rack": 30,
	"terrarium_dome": 42, "algae_tank": 28, "centrifuge": 42, "sample_fridge": 28,
	"uv_light": 42, "seedling_table": 44, "water_purifier": 42, "robot_arm": 44,
	"lab_console": 48, "ecg_monitor": 42, "culture_cylinder": 26, "herb_cabinet": 28,
	# engineering
	"cargo_crate": 28, "crate_stack": 44, "storage_shelf": 42, "tool_wall": 42,
	"generator": 46, "reactor_core": 48, "battery_bank": 28, "fuel_tank": 46,
	"gas_rack": 26, "smelter": 46, "laser_cutter": 48, "workbench_arm": 48,
	"conveyor": 64, "coolant_tank": 26, "forklift": 46, "winch": 28,
	"pipe_valve": 42, "fan_unit": 28, "tesla_coil": 26, "barrier": 28,
	"gear_press": 42, "lathe": 48, "gantry_crane": 56, "fuel_canister": 20,
	# lounge
	"sofa": 58, "armchair": 30, "bean_bag": 30, "coffee_table": 44,
	"arcade_cabinet": 28, "jukebox": 28, "pool_table": 62, "foosball": 50,
	"holo_chess": 46, "telescope": 28, "aquarium": 46, "bonsai": 26,
	"fountain": 40, "fireplace": 46, "potted_plant": 24, "alien_plant": 26,
	"crystal_planter": 26, "trophy_case": 42, "gold_bust": 22, "armillary": 24,
	"dance_pad": 42, "poker_table": 54, "dartboard": 26, "synth_keyboard": 42,
	"turntable": 26, "planetarium": 28, "hedge_wall": 42, "gem_case": 26,
	"star_chart": 28, "banner": 18,
}


const H_CAP := 52.0   # display height cap — nothing towers over the ~34px crew


static func width_of(id: String) -> float:
	return float(WIDTHS.get(id, int(ITEMS[id]["size"]) * 24))


static func dims_of(id: String) -> Vector2:
	## final DISPLAY size: box-fit of hand-tuned width + universal height cap
	var tex: Texture2D = ITEMS[id]["tex"]
	var ts := tex.get_size()
	var s := minf(width_of(id) / ts.x, H_CAP / ts.y)
	return ts * s


static func ids_in_category(cat: String) -> Array:
	## catalogue order is authoring order — stable for the modal grid
	var out: Array = []
	for id in ITEMS:
		if ITEMS[id]["cat"] == cat:
			out.append(id)
	return out


static func cost_text(id: String) -> String:
	var bits: PackedStringArray = []
	for sym in ITEMS[id]["cost"]:
		bits.append("%d %s" % [ITEMS[id]["cost"][sym], sym])
	return "  ".join(bits)
