class_name ElementFacts
## One-line trivia per element (all 103), shown in the inventory detail modal.
## Facts are real — condensed from common chemistry/Wikipedia knowledge.

const FACTS := {
	"H": "The lightest and most abundant element — about 90% of all atoms in the universe. It fuses in stars to make everything heavier.",
	"He": "Found in the Sun's spectrum before it was found on Earth. Cooled enough, it becomes a superfluid that climbs out of its container.",
	"Li": "The lightest metal — soft enough to cut, light enough to float on water. It powers nearly every rechargeable battery.",
	"Be": "Light, rigid and transparent to X-rays. Its mirrors fly on the James Webb telescope — but its dust is dangerously toxic.",
	"B": "Gives Pyrex glass its heat resistance, and its fibers stiffen aerospace composites. Essential for plant growth in tiny amounts.",
	"C": "The backbone of all known life. The very same atoms form both diamond and pencil graphite — only the bonds differ.",
	"N": "Makes up 78% of the air you breathe. Liquid nitrogen boils at −196°C, and its compounds are the heart of both fertilizer and explosives.",
	"O": "About 21% of the air and most of Earth's crust by mass. Without it there is no fire, no rust, and no breathing.",
	"F": "The most reactive element of all — it attacks almost everything. Tamed, it makes non-stick Teflon and toothpaste.",
	"Ne": "An inert noble gas that glows red-orange when charged — the original glow of neon signs.",
	"Na": "So soft you can cut it with a knife, so reactive it explodes in water. Yet it's half of ordinary table salt.",
	"Mg": "Burns with a blinding white light and is the lightest structural metal. It sits at the heart of every chlorophyll molecule.",
	"Al": "The most abundant metal in the crust. Once more precious than gold — and one of the few materials recyclable forever.",
	"Si": "The second most abundant element in the crust and the semiconductor behind every computer chip on the ship.",
	"P": "White phosphorus glows in the dark and ignites in air. It's also woven into your DNA and the ATP that powers your cells.",
	"S": "The 'brimstone' of legend — bright yellow, smelling of rotten eggs, and key to gunpowder and sulfuric acid.",
	"Cl": "A green, choking gas used as a weapon in WWI — yet it disinfects drinking water and forms half of table salt.",
	"Ar": "The most common noble gas in air (~1%). It fills light bulbs and shields molten metal during welding.",
	"K": "Reacts violently with water. It's vital for your nerves — and bananas are faintly radioactive thanks to potassium-40.",
	"Ca": "Builds your bones, seashells and limestone cliffs alike, and burns a bright orange-red.",
	"Sc": "Blended into aluminium it makes an ultralight, ultra-stiff alloy for bikes and jets — but it's rare and expensive.",
	"Ti": "As strong as steel at half the weight, and so body-friendly it's used for hip implants and jet frames.",
	"V": "Hardens steel into springs and tools. Its compounds paint a rainbow of colours across the test tube.",
	"Cr": "Gives stainless steel its shine and rust resistance — and it's the trace metal that makes rubies red.",
	"Mn": "Essential to making steel and the black paste inside old batteries. Also a trace nutrient you can't live without.",
	"Fe": "The most common element on Earth by mass — it forms the planet's molten core and carries oxygen in your blood.",
	"Co": "Colours glass and ceramics a deep cobalt blue and powers the cathodes of most EV batteries.",
	"Ni": "Rust-resistant and magnetic, it plates coins and armour and is a key ingredient in stainless steel.",
	"Cu": "Humanity's first metal and the best affordable conductor. Left outdoors it weathers to a green patina.",
	"Zn": "Coats steel to stop it rusting (galvanizing), is essential to your immune system, and is the other half of brass.",
	"Ga": "Melts in the warmth of your hand at 30°C. It's the semiconductor behind LEDs and high-speed chips.",
	"Ge": "The material of the first transistors, now vital to fibre-optic cables and infrared night-vision lenses.",
	"As": "History's infamous poison — yet it also dopes semiconductors and once tinted Victorian wallpaper green.",
	"Se": "Powered early photocopiers and solar cells. Vital in trace amounts, toxic in excess.",
	"Br": "One of only two elements liquid at room temperature — a dense, reddish, choking liquid.",
	"Kr": "A noble gas whose orange light once defined the length of the metre. It glows white in some lasers.",
	"Rb": "So soft and reactive it ignites in air. Its steady vibrations help keep atomic clocks on time.",
	"Sr": "Paints fireworks brilliant crimson. Its isotope Sr-90 is a telltale marker of nuclear fallout.",
	"Y": "Made the red glow in old colour TVs and strengthens high-temperature alloys and lasers.",
	"Zr": "Almost immune to corrosion, it clads nuclear fuel rods — and as cubic zirconia it fakes a convincing diamond.",
	"Nb": "Superconducting when cold, it toughens jet-engine alloys and anodizes into vivid jewellery colours.",
	"Mo": "One of the highest melting points of all metals; it toughens steel and drives essential enzymes in your body.",
	"Tc": "The first element ever made by humans — it has no stable isotope. Tc-99m lights up millions of medical scans each year.",
	"Ru": "Hardens platinum alloys and coats the platters of hard drives; a prized and rare catalyst.",
	"Rh": "The rarest and most valuable precious metal — mirror-bright and the active heart of catalytic converters.",
	"Pd": "Soaks up 900 times its own volume in hydrogen, scrubs car exhaust clean, and whitens white gold.",
	"Ag": "The best electrical and thermal conductor known, naturally antimicrobial — the metal of mirrors and coins.",
	"Cd": "Toxic and heavy, it once made brilliant yellow paints and the rechargeable NiCd batteries of old gadgets.",
	"In": "Soft enough to bend with a faint 'cry', it forms the transparent conductive coating on every touchscreen.",
	"Sn": "The metal that made the Bronze Age. It coats 'tin' cans and crackles audibly ('tin cry') when bent.",
	"Sb": "Hardens lead for batteries and bullets, and as kohl it lined the eyes of the ancient world.",
	"Te": "A rare metalloid that boosts thin-film solar panels — and gives anyone exposed to it powerful garlic breath.",
	"I": "Sublimes into a violet vapour. A vital thyroid nutrient and antiseptic, it's added to salt to prevent deficiency.",
	"Xe": "A heavy noble gas used as the propellant in spacecraft ion drives, as an anesthetic, and in brilliant headlights.",
	"Cs": "The most reactive metal, melting just above room temperature. Its vibration defines the exact length of one second.",
	"Ba": "Swallowed as a 'barium meal', it makes soft tissue show up on X-rays. It also burns fireworks green.",
	"La": "Gives its name to the lanthanides and sharpens high-end camera lenses and hybrid-car batteries.",
	"Ce": "The most abundant rare earth. It self-cleans oven catalysts and throws the sparks from a lighter's flint.",
	"Pr": "Tints glass and welding goggles green and joins neodymium in exceptionally strong magnets.",
	"Nd": "Forms the strongest permanent magnets ever made — inside every hard drive, earbud and electric motor.",
	"Pm": "A radioactive rare earth that once made watch dials glow. It has no stable isotope and is vanishingly rare.",
	"Sm": "Samarium-cobalt magnets keep their strength even when red hot, making them prized in aerospace.",
	"Eu": "The phosphor that gave old TVs their red — and the anti-counterfeit glow hidden in euro banknotes.",
	"Gd": "Injected as an MRI contrast agent and an extraordinary absorber of neutrons in reactors.",
	"Tb": "Powers green phosphors and 'magnetostrictive' devices that physically flex in a magnetic field.",
	"Dy": "Keeps the magnets in wind turbines and EV motors from weakening as they heat up.",
	"Ho": "Has the strongest magnetic pull of any element and drives precise surgical lasers.",
	"Er": "Amplifies light inside the fibre-optic cables that carry the internet across the oceans, and tints glass pink.",
	"Tm": "The rarest of the stable rare earths, used in portable X-ray machines and lasers.",
	"Yb": "Its atoms tick inside some of the most precise clocks ever built.",
	"Lu": "The densest and hardest rare earth — its crystals detect the gamma rays in PET medical scanners.",
	"Hf": "Extremely heat-tolerant, it forms reactor control rods and the ultra-thin insulator inside modern chips.",
	"Ta": "Stores huge charge in tiny capacitors, so it's in nearly every phone — and it's safe inside the human body.",
	"W": "Has the highest melting point of any metal (3422°C) — the glow of old light bulbs and the tip of drill bits.",
	"Re": "One of the rarest elements, it lets jet-engine turbine blades run white-hot without softening.",
	"Os": "The densest naturally occurring element — twice as heavy as lead — once tipping the finest fountain pens.",
	"Ir": "The most corrosion-proof metal. A worldwide layer of it in the rock marks the asteroid that ended the dinosaurs.",
	"Pt": "A precious, unreactive catalyst behind fuel cells and fine jewellery — and once the standard for the kilogram.",
	"Au": "Never tarnishes, conducts beautifully and hammers into gossamer sheets — humanity's money for thousands of years.",
	"Hg": "The only metal liquid at room temperature. Its vapour drove hat-makers 'mad', and it filled old thermometers.",
	"Tl": "The 'poisoner's poison' — tasteless, odourless and deadly. Once rat bait, now used in infrared detectors.",
	"Pb": "Dense, soft and easily melted, it plumbed ancient Rome (Latin plumbum) — but its toxicity has largely retired it.",
	"Bi": "Grows into dazzling iridescent rainbow crystals, soothes upset stomachs, and is a non-toxic stand-in for lead.",
	"Po": "Ferociously radioactive — Marie Curie named it for her native Poland. Infamous as an assassination poison.",
	"At": "The rarest naturally occurring element: less than a gram exists on all of Earth at once. Studied for cancer therapy.",
	"Rn": "A radioactive noble gas seeping up from decaying uranium. It pools in basements and is a leading cause of lung cancer.",
	"Fr": "The most unstable of the first 101 elements — only a handful of atoms have ever existed at one time.",
	"Ra": "Glows with its own eerie light. It once painted luminous watch dials — with tragic consequences for the painters.",
	"Ac": "Names the actinides and glows faint blue in the dark; now explored for targeted alpha cancer therapy.",
	"Pa": "Rare, toxic and radioactive — a fleeting step in the long decay of uranium into lead.",
	"Th": "A fertile nuclear fuel three times more abundant than uranium; it once made camping-lantern mantles glow.",
	"U": "The heaviest element found in nature. It fuels reactors and bombs, and its slow decay keeps Earth's core warm.",
	"Np": "The first element beyond uranium, named for the planet Neptune; a trace forms inside working reactors.",
	"Pu": "Forged in reactors, it powers deep-space probes and warheads alike — and is among the most toxic substances known.",
	"Am": "The tiny radioactive source at the heart of household smoke detectors.",
	"Cm": "Named for Marie and Pierre Curie, it glows from its own decay and powers instruments on space missions.",
	"Bk": "Named for Berkeley, California, it exists only to help synthesize still-heavier elements.",
	"Cf": "A potent neutron emitter used to start up reactors and to prospect for gold, silver and oil underground.",
	"Es": "First discovered in the fallout of the 1952 hydrogen-bomb test and named for Einstein; studied a few atoms at a time.",
	"Fm": "The heaviest element that can be made in a nuclear reactor, named for physicist Enrico Fermi.",
	"Md": "Named for Dmitri Mendeleev, father of the periodic table; made a single atom at a time in accelerators.",
	"No": "Named for Alfred Nobel; a fleeting, human-made element studied only in trace amounts.",
	"Lr": "Named for Ernest Lawrence, inventor of the cyclotron — the last of the actinide series.",
}


static func fact(sym: String) -> String:
	return FACTS.get(sym, "A rare element drawn from the dark. Records are incomplete out here.")
